version: '3'
services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./containerdata/mysql:/var/lib/mysql
      - ./importdata/mysql:/import
    environment:
      - MYSQL_ROOT_PASSWORD=root
