spring:
  datasource:
    password: pwd0123456789
    username: user
    url: jdbc:postgresql://localhost:5432/cityguide?createDatabaseIfNotExist=true
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true

authentication:
  jwt:
    secret:       secret
    issuer:       http://com.example.org
    audience:     http://com.example.org
    clockSkew:    10   # seconds
    validFor:     864000000 # seconds
    refreshLimit: 1    # times
    claimNames:
      authorities:  authorities
      refreshCount: refreshCount
      refreshLimit: refreshLimit